markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "lpig .Blog"
markdown: rdiscount

author: "lpig"
# atom-baseurl: "http://lpig.github.io"
#disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://photo.zjy-lpig.me
#  - title: Subscribe
#    class: fa fa-rss
#    href: /atom.xml

